[package]
name = "binary-layout-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
binary-layout = "4.0.2"
syn = { version = "2.0", features = ["parsing"] }
proc-macro2 = "1"
quote = "1.0"

[dev-dependencies]
trybuild = "1.0"
